version: "3.1"
services:
  mysql:
    image: mysql:oracle #run for Arm Architecture
    restart: always
    volumes:
      - /developer/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=085283480788
